#!/bin/zsh

echo "Installing/Updating nvim packages"
nvim --headless +PackagerClean +UpdatePackages

echo "Installing coc extensions"
cd "$HOME/.config/coc/extensions"
npm install --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
cd "$HOME"

echo "Updating coc"
nvim --headless +CocInstall +CocUpdateSync +CocRebuild +qall
