#!/bin/zsh

echo "Doing sparse checkout"
yadm gitconfig core.sparseCheckout true
yadm checkout --quiet

echo "Installing/Updating nvim packages"
nvim --headless +PackagerClean +UpdatePackages

echo "Installing coc extensions"
cd "$HOME/.config/coc/extensions"
npm install --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
cd "$HOME"

echo "Update coc"
nvim --headless +CocInstall +CocUpdateSync +CocRebuild +qall

echo "Deleting leftovers"
rm .zcompdump yadm
