#!/bin/zsh

# sparse checkout
yadm gitconfig core.sparseCheckout true
yadm checkout --quiet

nvim +PackagerInstall +PackagerUpdate +CocInstall +CocUpdateSync +CocRebuild +qall

cd "$HOME/.config/coc/extensions"
yarn install --frozen-lockfile
cd "$HOME"


nvim +CocInstall +CocUpdateSync +CocRebuild +qall

rm .zcompdump .yarnrc .nvimlog yadm
