#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Tk state=floating

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
feh --no-fehbg --bg-fill "$HOME/pictures/wallpaper.jpg"
launch_polybar
prismatik &
thunar --daemon &
redshift -l -28.29917:-54.26306 &
